### ISSUE TITLE
CSS variables

### ISSUE THREAD

**Issue by eopb** [rebo/seed_style_preview#3]
CSS variables are not yet implemented.

Here are some examples of what they could look like.

```rust
pub fn init() {
    GlobalStyle::default()
        .style(
            ":root",
            s().set_var("main-text-color", "lime"),
        )
        .activate_init_styles();
}
```
which will be equivalent too
```css
:root {
    --main-text-color: lime;
}
```
---

```rust
pub fn view(model: &state::Model) -> impl View<updates::Msg> {
    p![
        s().background_color(var("main-text-color")),
        "Hello World"   
     ]
}
```
which will be equivalent too
```css
... {
   background-color: var(--main-text-color);
}
```

---
Any feedback appreciated.
